# Generated by Django 5.2.4 on 2025-11-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_book_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Item',
        ),
    ]
