# Generated by Django 5.2.4 on 2025-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_title_item_name_remove_item_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='item',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
