# Generated by Django 5.2.7 on 2025-11-05 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_item_latitude_alter_item_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('pump_thr', models.FloatField()),
                ('humidity', models.FloatField()),
                ('temp', models.FloatField()),
                ('light', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='myapp.item')),
            ],
        ),
    ]
