# Generated by Django 5.2.4 on 2025-11-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='light',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pump_thr',
            field=models.FloatField(default=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temp',
            field=models.FloatField(default=0),
        ),
    ]
