# Generated by Django 5.2.4 on 2025-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sn',
            field=models.CharField(default='0', max_length=50, verbose_name='SN'),
        ),
    ]
