# Generated by Django 5.2.4 on 2025-12-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_sensor_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='light',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pump_thr',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temp',
            field=models.IntegerField(default=0),
        ),
    ]
